# Generated by Django 5.2.4 on 2025-08-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
