# Generated by Django 5.2.4 on 2025-08-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_user_id_note_author_alter_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='user',
        ),
    ]
